export const ACCOUNT_TYPE = {
    SAVINGS: 'SAVINGS',
    INVESTMENT: 'INVESTMENT',
    FIXED_DEPOSIT: 'FIXED_DEPOSIT',
    LOAN: 'LOAN',
    RECURRING_DEPOSIT: 'RECURRING_DEPOSIT',
    CASH: 'CASH',
    COMMODITY: 'COMMODITY',
    CRYPTO: 'CRYPTO',
    REAL_ESTATE: 'REAL_ESTATE',
    OTHER_ASSET: 'OTHER_ASSET'
} as const;

export const ACCOUNT_TYPES = [
    ACCOUNT_TYPE.SAVINGS,
    ACCOUNT_TYPE.INVESTMENT,
    ACCOUNT_TYPE.FIXED_DEPOSIT,
    ACCOUNT_TYPE.LOAN,
    ACCOUNT_TYPE.RECURRING_DEPOSIT,
    ACCOUNT_TYPE.CASH,
    ACCOUNT_TYPE.COMMODITY,
    ACCOUNT_TYPE.CRYPTO,
    ACCOUNT_TYPE.REAL_ESTATE,
    ACCOUNT_TYPE.OTHER_ASSET
] as const;

export const HOLDING_ACCOUNT_TYPES = [
    ACCOUNT_TYPE.INVESTMENT,
    ACCOUNT_TYPE.COMMODITY,
    ACCOUNT_TYPE.CRYPTO,
    ACCOUNT_TYPE.REAL_ESTATE,
    ACCOUNT_TYPE.OTHER_ASSET,
] as const;

export const ASSET_TYPE = {
    EQUITY: 'EQUITY',
    ETF: 'ETF',
    MUTUAL_FUND: 'MUTUAL_FUND',
    BOND: 'BOND',
    GOLD: 'GOLD',
    SILVER: 'SILVER',
    COMMODITY: 'COMMODITY',
    CRYPTO: 'CRYPTO',
    REAL_ESTATE: 'REAL_ESTATE',
    COLLECTIBLE: 'COLLECTIBLE',
    OTHER: 'OTHER',
} as const;

export const ASSET_TYPES = Object.values(ASSET_TYPE);

export const PRICE_SOURCE = {
    MANUAL: 'MANUAL',
    MARKET: 'MARKET',
} as const;

export const TRANSACTION_TYPE = {
    DEBIT: 'DEBIT',
    CREDIT: 'CREDIT',
    TRANSFER: 'TRANSFER'
} as const;

export const RULE_TYPE = {
    CATEGORIZATION: 'CATEGORIZATION',
    TRANSACTION: 'TRANSACTION',
    CALCULATION: 'CALCULATION',
    INTEREST: 'INTEREST'
} as const;

export const INTEREST_TREATMENT = {
    CAPITALIZE: 'CAPITALIZE',
    PAYOUT: 'PAYOUT',
    INTEREST_DUE: 'INTEREST_DUE',
} as const;

export const INTEREST_BALANCE_BASIS = {
    LEDGER_BALANCE: 'LEDGER_BALANCE',
    FIXED_PRINCIPAL: 'FIXED_PRINCIPAL',
    PRINCIPAL_OUTSTANDING: 'PRINCIPAL_OUTSTANDING',
} as const;

export const INTEREST_DAY_COUNT = {
    ACTUAL_365: 'ACTUAL_365',
    ACTUAL_ACTUAL: 'ACTUAL_ACTUAL',
    THIRTY_360: 'THIRTY_360',
} as const;

export const FREQUENCY = {
    DAILY: 'DAILY',
    WEEKLY: 'WEEKLY',
    MONTHLY: 'MONTHLY',
    QUARTERLY: 'QUARTERLY',
    YEARLY: 'YEARLY',
    ONE_TIME: 'ONE_TIME'
} as const;

export const TIME_RANGES = ['currentMonth', 'last30Days', 'lastMonth', 'allTime'] as const;

export const DEFAULT_CURRENCY = 'USD';
export const DEFAULT_ACCRUAL_DAY = '1';
