"""Drop balance

Revision ID: 47a4d3c2bf6b
Revises: e9b1dcd5cec6
Create Date: 2026-06-19 23:52:48.109592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '47a4d3c2bf6b'
down_revision: Union[str, Sequence[str], None] = 'e9b1dcd5cec6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('balance', mysql.DECIMAL(precision=15, scale=2), nullable=False))
    # ### end Alembic commands ###
