"""Add RECURRING_DEPOSIT account type

Revision ID: bc8a33302897
Revises: 47a4d3c2bf6b
Create Date: 2026-06-20 22:57:20.355344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bc8a33302897'
down_revision: Union[str, Sequence[str], None] = '47a4d3c2bf6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_accounts')
    op.drop_table('fixed_deposit_accounts')
    op.drop_table('savings_accounts')
    # ### end Alembic commands ###
    op.execute("ALTER TABLE accounts MODIFY COLUMN account_type ENUM('SAVINGS', 'INVESTMENT', 'LOAN', 'FIXED_DEPOSIT', 'RECURRING_DEPOSIT') NOT NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_accounts',
    sa.Column('account_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('balance', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('interest_rate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('min_balance', mysql.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('interest_accrual_day', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], name=op.f('savings_accounts_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fixed_deposit_accounts',
    sa.Column('account_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('principal_amount', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('interest_rate', mysql.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('maturity_date', sa.DATE(), nullable=False),
    sa.Column('maturity_amount', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('interest_accrual_day', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], name=op.f('fixed_deposit_accounts_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('loan_accounts',
    sa.Column('account_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('loan_amount', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('principal_balance', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('interest_balance', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('outstanding_amount', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('interest_rate', mysql.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('tenure_months', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('emi_amount', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('emi_start_date', sa.DATE(), nullable=True),
    sa.Column('interest_accrual_day', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], name=op.f('loan_accounts_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
    op.execute("ALTER TABLE accounts MODIFY COLUMN account_type ENUM('SAVINGS', 'INVESTMENT', 'LOAN', 'FIXED_DEPOSIT') NOT NULL")
