"""Optimized schema

Revision ID: e9b1dcd5cec6
Revises: 
Create Date: 2026-06-19 23:43:05.376553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e9b1dcd5cec6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=5), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('settings',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('default_currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('exchange_provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('account_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_type', sa.Enum('SAVINGS', 'INVESTMENT', 'LOAN', 'FIXED_DEPOSIT', name='accounttype'), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_interest_enabled', sa.Boolean(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_accounts_account_type'), 'accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name', 'user_id', name='unique_category_per_user')
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_index(op.f('ix_category_user_id'), 'category', ['user_id'], unique=False)
    op.create_table('investment_holdings',
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('stock_exchange', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('last_price_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('holding_id')
    )
    op.create_index(op.f('ix_investment_holdings_account_id'), 'investment_holdings', ['account_id'], unique=False)
    op.create_index(op.f('ix_investment_holdings_symbol'), 'investment_holdings', ['symbol'], unique=False)
    op.create_table('rules',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('rule_type', sa.Enum('CATEGORIZATION', 'TRANSACTION', 'CALCULATION', name='ruletype'), nullable=False),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('additional_info', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('transfer_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.account_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_transfer_id'), 'transactions', ['transfer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transfer_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('rules')
    op.drop_index(op.f('ix_investment_holdings_symbol'), table_name='investment_holdings')
    op.drop_index(op.f('ix_investment_holdings_account_id'), table_name='investment_holdings')
    op.drop_table('investment_holdings')
    op.drop_index(op.f('ix_category_user_id'), table_name='category')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_type'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('currency')
    # ### end Alembic commands ###
